// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Accounts struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	Balance   int64     `json:"balance"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"createdAt"`
}

type Entries struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"accountID"`
	// can be negative or positive.
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"createdAt"`
}

type Transfers struct {
	ID            int64         `json:"id"`
	FromAccountID int64         `json:"fromAccountID"`
	ToAccountID   sql.NullInt64 `json:"toAccountID"`
	// must be positive.
	Amount int64 `json:"amount"`
}
